package com.zefun.web.entity;

/**
 * 企业微信设置
* @author 高国藩
* @date 2016年5月31日 上午9:43:54
 */
public class StoreWechat {
    /** 企业账号 */
    private String storeAccount;

    /** 公众号原始id */
    private String wechatId;

    /** 公众号应用ID */
    private String wechatAppid;

    /** 公众号应用密钥 */
    private String wechatAppsecret;

    /** 客户预约申请通知 */
    private String tmAppointApply;

    /** 客户预约结果通知 */
    private String tmAppointResult;

    /** 客户预约到时提醒 */
    private String tmAppointRemind;

    /** 客户充值结果提醒 */
    private String tmChargeResult;

    /** 客户结账信息通知 */
    private String tmPaymentInfo;

    /** 员工服务移交通知 */
    private String tmServiceTurn;
    
    /** 服务计划推送通知 */
    private String tmServiceTopic;

    /** 优惠券到期提醒 */
    private String tmCouponOverdue;
    
    /** 微信支付商户ID*/
    private String appId;
    /** 微信支付商户ID*/
    private String mchId;
    /** 微信支付商户ID*/
    private String mchKey;

    
    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getMchId() {
        return mchId;
    }

    public void setMchId(String mchId) {
        this.mchId = mchId;
    }

    public String getMchKey() {
        return mchKey;
    }

    public void setMchKey(String mchKey) {
        this.mchKey = mchKey;
    }

    public String getStoreAccount() {
        return storeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.store_account
     *
     * @param storeAccount the value for store_wechat.store_account
     *
     * @mbggenerated
     */
    public void setStoreAccount(String storeAccount) {
        this.storeAccount = storeAccount == null ? null : storeAccount.trim();
    }

    public String getWechatId() {
        return wechatId;
    }

    
    public String getTmServiceTopic() {
        return tmServiceTopic;
    }

    public void setTmServiceTopic(String tmServiceTopic) {
        this.tmServiceTopic = tmServiceTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.wechat_id
     *
     * @param wechatId the value for store_wechat.wechat_id
     *
     * @mbggenerated
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    public String getWechatAppid() {
        return wechatAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.wechat_appid
     *
     * @param wechatAppid the value for store_wechat.wechat_appid
     *
     * @mbggenerated
     */
    public void setWechatAppid(String wechatAppid) {
        this.wechatAppid = wechatAppid == null ? null : wechatAppid.trim();
    }

    public String getWechatAppsecret() {
        return wechatAppsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.wechat_appsecret
     *
     * @param wechatAppsecret the value for store_wechat.wechat_appsecret
     *
     * @mbggenerated
     */
    public void setWechatAppsecret(String wechatAppsecret) {
        this.wechatAppsecret = wechatAppsecret == null ? null : wechatAppsecret.trim();
    }

    public String getTmAppointApply() {
        return tmAppointApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_appoint_apply
     *
     * @param tmAppointApply the value for store_wechat.tm_appoint_apply
     *
     * @mbggenerated
     */
    public void setTmAppointApply(String tmAppointApply) {
        this.tmAppointApply = tmAppointApply == null ? null : tmAppointApply.trim();
    }

    public String getTmAppointResult() {
        return tmAppointResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_appoint_result
     *
     * @param tmAppointResult the value for store_wechat.tm_appoint_result
     *
     * @mbggenerated
     */
    public void setTmAppointResult(String tmAppointResult) {
        this.tmAppointResult = tmAppointResult == null ? null : tmAppointResult.trim();
    }

    public String getTmAppointRemind() {
        return tmAppointRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_appoint_remind
     *
     * @param tmAppointRemind the value for store_wechat.tm_appoint_remind
     *
     * @mbggenerated
     */
    public void setTmAppointRemind(String tmAppointRemind) {
        this.tmAppointRemind = tmAppointRemind == null ? null : tmAppointRemind.trim();
    }

    public String getTmChargeResult() {
        return tmChargeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_charge_result
     *
     * @param tmChargeResult the value for store_wechat.tm_charge_result
     *
     * @mbggenerated
     */
    public void setTmChargeResult(String tmChargeResult) {
        this.tmChargeResult = tmChargeResult == null ? null : tmChargeResult.trim();
    }

    public String getTmPaymentInfo() {
        return tmPaymentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_payment_info
     *
     * @param tmPaymentInfo the value for store_wechat.tm_payment_info
     *
     * @mbggenerated
     */
    public void setTmPaymentInfo(String tmPaymentInfo) {
        this.tmPaymentInfo = tmPaymentInfo == null ? null : tmPaymentInfo.trim();
    }

    public String getTmServiceTurn() {
        return tmServiceTurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_service_turn
     *
     * @param tmServiceTurn the value for store_wechat.tm_service_turn
     *
     * @mbggenerated
     */
    public void setTmServiceTurn(String tmServiceTurn) {
        this.tmServiceTurn = tmServiceTurn == null ? null : tmServiceTurn.trim();
    }

    public String getTmCouponOverdue() {
        return tmCouponOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_wechat.tm_coupon_overdue
     *
     * @param tmCouponOverdue the value for store_wechat.tm_coupon_overdue
     *
     * @mbggenerated
     */
    public void setTmCouponOverdue(String tmCouponOverdue) {
        this.tmCouponOverdue = tmCouponOverdue == null ? null : tmCouponOverdue.trim();
    }
}