// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    var brick;
    brick = "<div class='brick small'></div>";
    jQuery(document).on("click", ".gridly .brick", function(event) {
      var jQuerythis, size;
      event.preventDefault();
      event.stopPropagation();
      jQuerythis = jQuery(this);
     
    
      if (jQuerythis.hasClass('small')) {
        size = 140;
      }
    
      jQuerythis.data('width', size);
      jQuerythis.data('height', size);
      return jQuery('.gridly').gridly('layout');
    });

 
    return jQuery('.gridly').gridly();
  });

}).call(this);
