package com.zefun.web.entity;

import java.math.BigDecimal;

public class MemberComboRecord {
    /**
     *  记录标识
     */
    private Integer recordId;

    /**
     *  会员标识
     */
    private Integer memberId;

    /**
     *  套餐标识
     */
    private Integer comboId;

    /**
     *  门店标识
     */
    private Integer storeId;

    /**
     *  订单明细标识
     */
    private Integer detailId;

    /**
     *  套餐名称
     */
    private String comboName;

    /**
     *  套餐价格
     */
    private BigDecimal comboPrice;

    /**
     *  套餐图片
     */
    private String comboImage;

    /**
     *  项目总价
     */
    private BigDecimal projectAmount;

    /**
     *  项目数量
     */
    private Integer projectCount;

    /**
     *  剩余数量
     */
    private Integer remainingCount;

    /**
     *  过期时间
     */
    private String overdueTime;

    /**
     *  创建时间
     */
    private String createTime;

    /**
     *  是否删除(0:未删除,1:已删除)
     */
    private Integer isDeleted;

    /**
     *  修改时间
     */
    private String updateTime;

    /**
     *  最后操作人标识
     */
    private Integer lastOperatorId;

    /**
     *  是否已过期（0未过期，1已过期）
     */
    private Integer isTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.record_id
     *
     * @return the value of member_combo_record.record_id
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.record_id
     *
     * @param recordId the value for member_combo_record.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.member_id
     *
     * @return the value of member_combo_record.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.member_id
     *
     * @param memberId the value for member_combo_record.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.combo_id
     *
     * @return the value of member_combo_record.combo_id
     *
     * @mbggenerated
     */
    public Integer getComboId() {
        return comboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.combo_id
     *
     * @param comboId the value for member_combo_record.combo_id
     *
     * @mbggenerated
     */
    public void setComboId(Integer comboId) {
        this.comboId = comboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.store_id
     *
     * @return the value of member_combo_record.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.store_id
     *
     * @param storeId the value for member_combo_record.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.detail_id
     *
     * @return the value of member_combo_record.detail_id
     *
     * @mbggenerated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.detail_id
     *
     * @param detailId the value for member_combo_record.detail_id
     *
     * @mbggenerated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.combo_name
     *
     * @return the value of member_combo_record.combo_name
     *
     * @mbggenerated
     */
    public String getComboName() {
        return comboName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.combo_name
     *
     * @param comboName the value for member_combo_record.combo_name
     *
     * @mbggenerated
     */
    public void setComboName(String comboName) {
        this.comboName = comboName == null ? null : comboName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.combo_price
     *
     * @return the value of member_combo_record.combo_price
     *
     * @mbggenerated
     */
    public BigDecimal getComboPrice() {
        return comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.combo_price
     *
     * @param comboPrice the value for member_combo_record.combo_price
     *
     * @mbggenerated
     */
    public void setComboPrice(BigDecimal comboPrice) {
        this.comboPrice = comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.combo_image
     *
     * @return the value of member_combo_record.combo_image
     *
     * @mbggenerated
     */
    public String getComboImage() {
        return comboImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.combo_image
     *
     * @param comboImage the value for member_combo_record.combo_image
     *
     * @mbggenerated
     */
    public void setComboImage(String comboImage) {
        this.comboImage = comboImage == null ? null : comboImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.project_amount
     *
     * @return the value of member_combo_record.project_amount
     *
     * @mbggenerated
     */
    public BigDecimal getProjectAmount() {
        return projectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.project_amount
     *
     * @param projectAmount the value for member_combo_record.project_amount
     *
     * @mbggenerated
     */
    public void setProjectAmount(BigDecimal projectAmount) {
        this.projectAmount = projectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.project_count
     *
     * @return the value of member_combo_record.project_count
     *
     * @mbggenerated
     */
    public Integer getProjectCount() {
        return projectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.project_count
     *
     * @param projectCount the value for member_combo_record.project_count
     *
     * @mbggenerated
     */
    public void setProjectCount(Integer projectCount) {
        this.projectCount = projectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.remaining_count
     *
     * @return the value of member_combo_record.remaining_count
     *
     * @mbggenerated
     */
    public Integer getRemainingCount() {
        return remainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.remaining_count
     *
     * @param remainingCount the value for member_combo_record.remaining_count
     *
     * @mbggenerated
     */
    public void setRemainingCount(Integer remainingCount) {
        this.remainingCount = remainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.overdue_time
     *
     * @return the value of member_combo_record.overdue_time
     *
     * @mbggenerated
     */
    public String getOverdueTime() {
        return overdueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.overdue_time
     *
     * @param overdueTime the value for member_combo_record.overdue_time
     *
     * @mbggenerated
     */
    public void setOverdueTime(String overdueTime) {
        this.overdueTime = overdueTime == null ? null : overdueTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.create_time
     *
     * @return the value of member_combo_record.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.create_time
     *
     * @param createTime the value for member_combo_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.is_deleted
     *
     * @return the value of member_combo_record.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.is_deleted
     *
     * @param isDeleted the value for member_combo_record.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.update_time
     *
     * @return the value of member_combo_record.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.update_time
     *
     * @param updateTime the value for member_combo_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.last_operator_id
     *
     * @return the value of member_combo_record.last_operator_id
     *
     * @mbggenerated
     */
    public Integer getLastOperatorId() {
        return lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.last_operator_id
     *
     * @param lastOperatorId the value for member_combo_record.last_operator_id
     *
     * @mbggenerated
     */
    public void setLastOperatorId(Integer lastOperatorId) {
        this.lastOperatorId = lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_combo_record.is_time
     *
     * @return the value of member_combo_record.is_time
     *
     * @mbggenerated
     */
    public Integer getIsTime() {
        return isTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_combo_record.is_time
     *
     * @param isTime the value for member_combo_record.is_time
     *
     * @mbggenerated
     */
    public void setIsTime(Integer isTime) {
        this.isTime = isTime;
    }
}