package com.zefun.web.mapper;


import java.util.Map;

import com.zefun.web.entity.MemberComboProject;

public interface MemberComboProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int insert(MemberComboProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int insertSelective(MemberComboProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    MemberComboProject selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberComboProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberComboProject record);

    /**
     * 修改状态吗
    * @author 高国藩
    * @date 2016年8月20日 下午3:11:24
    * @param recordIds recordIds
     */
    void updateByRecordIds(Map<String, String> map);
}