package com.zefun.web.mapper;

import com.zefun.web.entity.MemberComboRecord;

public interface MemberComboRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int insert(MemberComboRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int insertSelective(MemberComboRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    MemberComboRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberComboRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberComboRecord record);
}