package com.zefun.web.mapper;

import java.util.List;
import java.util.Map;

import com.zefun.web.entity.MemberComboRecord;

public interface MemberComboRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int insert(MemberComboRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int insertSelective(MemberComboRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    MemberComboRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberComboRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberComboRecord record);

    /**
     * 查询所有的未过期和未删除的记录
    * @author 高国藩
    * @date 2016年8月20日 下午2:52:00
    * @return
     */
    List<MemberComboRecord> selectAll(String date);

    /**
     * 将当前过期的设置为过期
    * @author 高国藩
    * @date 2016年8月20日 下午3:33:29
    * @param reviceDate
     */
    void updateByDate(Map<String, String> map);
}