package com.zefun.web.mapper;

import com.zefun.web.entity.MemberComboProject;

public interface MemberComboProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int insert(MemberComboProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int insertSelective(MemberComboProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    MemberComboProject selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberComboProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_combo_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberComboProject record);
}